export default [
  {
    moodTrackingStepId: 5,
    organizationId: 1,
    fieldType: "",
    stepName: "How do you feel today?",
    logo: "",
    stepDescription: "",
    isRequired: true,
    nextStep: 1,
    stepNumber: 0,
    parentId: null,
    fieldName: "",
    moodTrackingStepOptions: [
      {
        moodTrackingStepOptionId: 1,
        optionValue: "Feeling down",
        optionLabel: "",
        logo: "https://zumlofilestorage.blob.core.windows.net/static-files/MoodTracking_FeelingDown.png",
        optionOrder: 1,
      },
      {
        moodTrackingStepOptionId: 2,
        optionValue: "Feeling low",
        optionLabel: "",
        logo: "https://zumlofilestorage.blob.core.windows.net/static-files/MoodTracking_FeelingLow.png",
        optionOrder: 2,
      },
      {
        moodTrackingStepOptionId: 3,
        optionValue: "Neutral",
        optionLabel: "",
        logo: "https://zumlofilestorage.blob.core.windows.net/static-files/MoodTracking_Neutral.png",
        optionOrder: 3,
      },
      {
        moodTrackingStepOptionId: 4,
        optionValue: "Feeling happy",
        optionLabel: "",
        logo: "https://zumlofilestorage.blob.core.windows.net/static-files/MoodTracking_FeelingHappy.png",
        optionOrder: 4,
      },
      {
        moodTrackingStepOptionId: 5,
        optionValue: "Feeling extremely joyful",
        optionLabel: "",
        logo: "https://zumlofilestorage.blob.core.windows.net/static-files/MoodTracking_FeelingextremelyJoyful.png",
        optionOrder: 5,
      },
    ],
  },
  {
    moodTrackingStepId: 9,
    organizationId: 1,
    fieldType: "",
    stepName: "Title",
    logo: "",
    stepDescription: "Title",
    isRequired: true,
    nextStep: 1,
    stepNumber: 0,
    parentId: 5,
    fieldName: "",
    moodTrackingStepOptions: [],
  },
  {
    moodTrackingStepId: 12,
    organizationId: 1,
    fieldType: "",
    stepName: "Description",
    logo: "",
    stepDescription: "Description",
    isRequired: true,
    nextStep: 2,
    stepNumber: 1,
    parentId: 5,
    fieldName: "",
    moodTrackingStepOptions: [],
  },
];
