//community module APIs
export const API_FUN_NAMES = {
  globalJsonByCategoryName: "globalJsonByCategoryName",
  getCommunityProfile: "getCommunityProfile",
  GetGlobalCodesByCategoryName: "GetGlobalCodesByCategoryName",
  getSeekerPersonalInfo: "getSeekerPersonalInfo",
  updateCommunityProfile: "updateCommunityProfile",
  suggestedGroups: "suggestedGroups",
  likeFeed: "likeFeed",
  forLikes: "forLikes",
  SaveOrUnSaveFeedAPI: "SaveOrUnSaveFeedAPI",
  ForSaveOrUnsaveFeeds: "ForSaveOrUnsaveFeeds",
  postStatus: "postStatus",
  PostDeleteOrUnsavedFromFeedDetails: "PostDeleteOrUnsavedFromFeedDetails",
  DeleteFeedOrFeedShare: "DeleteFeedOrFeedShare",
  shareFeed: "shareFeed",
  createdOrJoinedGroupList: "createdOrJoinedGroupList",
  connectedUserList: "connectedUserList",
  joinGroup: "joinGroup",
  join: "join",
  LeaveGroup: "LeaveGroup",
  leave: "leave",
  removeJoinRequest: "removeJoinRequest",
  createFeed: "createFeed",
  updateFeed: "updateFeed",
  createCommunityProfile: "createCommunityProfile",
  communityUserList: "communityUserList",
  addGroupMembers: "addGroupMembers",
  removeGroupMembers: "removeGroupMembers",
  getChat: "getChat",
  SavedFeedsList: "SavedFeedsList",
  groupDetailsById: "groupDetailsById",
  feedsByGroupId: "feedsByGroupId",
  deleteGroup: "deleteGroup",
  privateAndPublicGroupList: "privateAndPublicGroupList",
  acceptOrRejectInvite: "acceptOrRejectInvite",
  acceptOrRejectConnectionRequest: "acceptOrRejectConnectionRequest",
  communityActivities: "communityActivities",
  userProfileById: "userProfileById",
  searchAny: "searchAny",
  createGroup: "createGroup",
  updateGroup: "updateGroup",
  InsertNewCategoryAPI: "InsertNewCategoryAPI",
  getFeedById: "getFeedById",
  createConnection: "createConnection",
  feedReport: "feedReport",

  //Profile module APIs
  changePassword: "changePassword",
  seekerDetails: "seekerDetails",
  GetConsentFormByType: "GetConsentFormByType",
  deleteAccount: "deleteAccount",
  Signup_api: "Signup_api",
  onSaveEducationData: "onSaveEducationData",
  saveFinancialGoalsData: "saveFinancialGoalsData",
  getAllGlobalCodesWithCategory: "getAllGlobalCodesWithCategory",
  GetAllFormImages: "GetAllFormImages",
  onSaveMentalHealthData: "onSaveMentalHealthData",
  onSavePhysicalHealthData: "onSavePhysicalHealthData",
  saveProfessionalGoalsData: "saveProfessionalGoalsData",
  saveEnhancingData: "saveEnhancingData",
  saveDevelopingData: "saveDevelopingData",
  GetUserMedicalHistory: "GetUserMedicalHistory",
  MedicalHistoryStepAnswer: "MedicalHistoryStepAnswer",
  GetMedicalHistoryStepsByCodeId: "GetMedicalHistoryStepsByCodeId",
  getOnboardingSteps: "getOnboardingSteps",
  getWellnessPlanDetails: "getWellnessPlanDetails",

  //subcription module APIs
  getSubscriptionPlans: "getSubscriptionPlans",
  buySubscription: "buySubscription",
  GetUserActivityProgress: "GetUserActivityProgress",
  GetActivitiesQuestionsByCategoryIdApi:
    "GetActivitiesQuestionsByCategoryIdApi",
  GetEditableActivityQuestionsByIdAPI: "GetEditableActivityQuestionsByIdAPI",
  GetUserActivityProgressById: "GetUserActivityProgressById",
  GetUserGoalProgressById: "GetUserGoalProgressById",

  LinkRecommendationItems: "LinkRecommendationItems",

  //dashboard
  GetUserIndividualGoalsList: "GetUserIndividualGoalsList",
  GetMobileDashboardPrompts: "GetMobileDashboardPrompts",
  GetResourceLibraryTemplate: "GetResourceLibraryTemplate",
  GetUserMobileDashboardDetailsByDate: "GetUserMobileDashboardDetailsByDate",
  GetUserMobileDashboardQuotesByDate: "GetUserMobileDashboardQuotesByDate",
  getVitalsActivityStatus: "getVitalsActivityStatus",
  seekerOnboardingStepAnswer: "seekerOnboardingStepAnswer",
  SaveOnboardingExplorerSteps: "SaveOnboardingExplorerSteps",
  DeleteActivityByIdApi: "DeleteActivityByIdApi",
  GetGoalsGraphDataByDate: "GetGoalsGraphDataByDate",
  GetUserPlannerOnboardingResponse: "GetUserPlannerOnboardingResponse",
  PredefinedActivitiesToUser: "PredefinedActivitiesToUser",
  getRegenerateOnboardingDetails: "getRegenerateOnboardingDetails",
  GetDailyAffirmations: "GetDailyAffirmations",
  onSkipQuestion: "onSkipQuestion",
  onSavePlanner_Explorer: "onSavePlanner_Explorer",
  getMoodJournalingQuestion: "getMoodJournalingQuestion",
  saveMoodJournalingQuestion: "saveMoodJournalingQuestion",
  SaveActivityHistoryDetail: "SaveActivityHistoryDetail",
  GetUserSkippedCategory: "GetUserSkippedCategory",
  GetVitalsActivityStatusSummary: "GetVitalsActivityStatusSummary",
  getVitalSummary: "getVitalSummary",
  MoodJournalAiQuestion: "MoodJournalAiQuestion",
  SaveConsentForm: "SaveConsentForm",
  ValidateUserEmail: "ValidateUserEmail",
  StartFreeTrial: "StartFreeTrial",
  GetHabitsDetails: "GetHabitsDetails",
  saveHabitTrackingAPI: "saveHabitTrackingAPI",
  createHabitAPI: "createHabitAPI",
  getHabitCategories: "getHabitCategories",
  getHabitTrackingForGraphAPI: "getHabitTrackingForGraphAPI",
  getHabitProgressAPI: "getHabitProgressAPI",
  recommendationVideosAndBooks: "recommendationVideosAndBooks",
  recommendationCategories: "recommendationCategories",
  BookRecommendations: "BookRecommendations",
  GenerateRecommendationItems: "GenerateRecommendationItems",
  getHabitProgressByIdAPI: "getHabitProgressByIdAPI",
};

export const SOCKET_FUN_NAME = {
  communityChat: "communityChat",
  GetConnectionId: "GetConnectionId",
  ReceiveChatMessage: "ReceiveChatMessage",
  SendMessage: "SendMessage",
  connectedUserList: "connectedUserList",
  login: "login",
};
