export const DD_MMM_YYYY = "DD-MMM-YYYY";
export const MM_DD_YYYY = "MM-DD-YYYY";
export const YYYY_MM_DD = "YYYY-MM-DD";
export const YYYY_MMM_DD = "YYYY_MMM_DD";
export const DDsMMMsYYYY = "DD MMM YYYY";
export const DDsMMsYYYY = "DD MM YYYY";
export const MMMsYYYY = "MMM YYYY";
export const LLL = "LLL";
export const MMMsDosYY = "MMM Do YY";
export const MMMsDosYYYY = "MMM Do YYYY";
export const DosMMMsYYYY = "Do MMM YYYY";
export const dddcDosMMMsYYYY = "ddd,Do MMM YYYY";
export const DDsMMMsYYYYsHHcMMsA = "DD MMM YYYY hh:mm A";
export const DD_MMM_YY = "DD-MMM-YY";
export const DD_MMM_YYYY_ = "MMM DD,YYYY";
export const DD_MM_YY = "DD-MM-YY";
export const MMsYY = "MM/YY";
export const MMMM_D = "MMMM D"; // February 28
export const DD_MM_YYYY = "DD-MM-YYYY";
export const ddd_DD_MMM_MMM = "ddd, DD MMM YYYY"; // Mon, 08 Jan 2024
export const MM_DD_YYY = "MM-DD-YYYY"; // Mon, 08 Jan 2024
export const MMMM = "MMMM"; // Mon, 08 Jan 2024
export const ddd_ = "ddd";
export const MMMM_DD_YYYY = "MMMM DD,YYYY"; //June 09,2025
export const hh_mm_A = "hh:mm A"; //10:00 AM
export const hh_mm_a = "hh:mm A"; //10:00 am
export const HH_mm_a = "HH:mm A"; //22:00 pm
export const HH_mm_A = "HH:mm A"; //22:00 PM
