export const activityData: any = {
  data: {
    result: {
      userId: 0,
      timePeriod: "Week",
      resultFor: "Activities",
      progressStatus: {
        title: "",
        description: "",
        logo: "",
      },
      activityProgressDetails: [
        {
          id: 209,
          title: "Morning Meditation",
          activityType: "Mindfulness",
          duration: "30 mins",
          startDate: "",
          endDate: "",
          progressBreakdown: [
            {
              label: "2025-05-17 (Sat)",
              progressValue: "",
              progressPercentage: 25.333333333333336,
            },
            {
              label: "2025-05-18 (Sun)",
              progressValue: "",
              progressPercentage: 30,
            },
            {
              label: "2025-05-19 (Mon)",
              progressValue: "",
              progressPercentage: 40,
            },
            {
              label: "2025-05-20 (Tue)",
              progressValue: "",
              progressPercentage: 50,
            },
            {
              label: "2025-05-21 (Wed)",
              progressValue: "",
              progressPercentage: 30,
            },
            {
              label: "2025-05-22 (Thu)",
              progressValue: "",
              progressPercentage: 80,
            },
            {
              label: "2025-05-23 (Fri)",
              progressValue: "",
              progressPercentage: 100,
            },
          ],
          description: "Need to do daily morning meditation",
          scheduleTime: ["06:00 AM"],
          logo: "",
          frequency: "Daily",
          frequencyCount: "1",
          graphType: "BarGraph",
          activityHistory: [],
        },
        {
          id: 210,
          title: "Weekly Exercise Routine",
          activityType: "Physical Activity",
          duration: "60 mins",
          startDate: "",
          endDate: "",
          progressBreakdown: [
            {
              label: "2025-05-17 (Sat)",
              progressValue: "",
              progressPercentage: 25.333333333333336,
            },
            {
              label: "2025-05-18 (Sun)",
              progressValue: "",
              progressPercentage: 30,
            },
            {
              label: "2025-05-19 (Mon)",
              progressValue: "",
              progressPercentage: 40,
            },
            {
              label: "2025-05-20 (Tue)",
              progressValue: "",
              progressPercentage: 50,
            },
            {
              label: "2025-05-21 (Wed)",
              progressValue: "",
              progressPercentage: 30,
            },
            {
              label: "2025-05-22 (Thu)",
              progressValue: "",
              progressPercentage: 80,
            },
            {
              label: "2025-05-23 (Fri)",
              progressValue: "",
              progressPercentage: 100,
            },
          ],
          description: "Need to do weekly exercise routine",
          scheduleTime: ["07:00 AM"],
          logo: "",
          frequency: "Weekly",
          frequencyCount: "3",
          graphType: "RadialBar",
          activityHistory: [],
        },
      ],
    },
    id: 8437,
    status: 5,
    isCanceled: false,
    isCompleted: true,
    isCompletedSuccessfully: true,
    creationOptions: 0,
    isFaulted: false,
  },
  statusCode: 200,
  message: "Record returned successfully.",
  success: true,
};
