import { ScrollView } from "react-native";
import React, { ReactElement, useEffect, useState } from "react";
import colors from "../../constant/colors";
import { moderateScale } from "../../constant/responsiveStyle";
import ScreenWrapper from "../../components/SafeArea/SafeAreaWrapper";
import UserInfo from "./UserInfo";
import HeaderWellnessPlan from "./HeaderWellnessPlan";
import ButtonsBtm from "./ButtonsBtm";
import { imagePath } from "../../assets/png/imagePath";
import WellnessOverviewCard from "./WellnessOverviewCard";
import styles from "./styles";
import allActions from "../../redux/actions";
import { useDispatch } from "react-redux";
import ToastMsg from "../../components/Hooks/useToast";
import LoaderSurf from "../../components/Loader/LoaderSurf";
import CommonLoader from "../../components/Loader";

interface Props {
  navigation?: any;
}
const WellnessGoal: React.FC<Props> = ({ navigation }): ReactElement => {
  const dispatch = useDispatch();
  const [isLoading, setisLoading] = useState(false);
  const [isData, setisData] = useState(false);

  const [wellnessPlanData, setWellnessPlanData] = useState<any>();
  useEffect(() => {
    GetSeekerWellnessPlanDetailsAsync_api();
  }, []);
  useEffect(() => {
    setisLoading(true);
    setTimeout(() => {
      setisLoading(false);
      setisData(true);
    }, 10000);
  }, []);
  const GetSeekerWellnessPlanDetailsAsync_api = async () => {
    setisLoading(true);

    let requestbody = {};
    // console.log("cehck requestbody", requestbody);
    allActions.seekerDetails
      .GetSeekerWellnessPlanDetailsAsync(
        dispatch,
        null,
        "GetSeekerWellnessPlanDetailsAsync_api"
      )
      .then((response: any) => {
        console.log(
          "check ===>GetSeekerWellnessPlanDetailsAsync_api",
          response?.data[0]
        );
        if (response.statusCode == 200) {
          // setisLoading(false);

          setWellnessPlanData(response?.data[0]);
          // setPrimaryGoalsData(response?.data[0])
          // setPrimaryGoalsData(response?.data[0])
          // setPrimaryGoalsData(response?.data[0])
        } else {
          setisLoading(false);
          ToastMsg("error", "Error", response?.message);
        }
      })
      .catch((err) => {
        console.log("check error for ", err);

        setisLoading(false);
        ToastMsg("error", "Error", err?.message);
      });
  };

  const [activitiesData, setActivitiesData] = useState([]);
  const [primaryGoalsData, setPrimaryGoalsData] = useState([]);
  const [basicInfoData, setBasicInfoData] = useState([
    {
      id: 1,
      title: "Anxiety",
    },
    {
      id: 2,
      title: "Generated by Zumlo",
    },
  ]);
  const [secondaryGoalsData, setSecondaryGoalsData] = useState([]);
  return (
    console.log(
      "wellnessPlanData?.wellnessActivity",
      wellnessPlanData?.wellnessActivity
    ),
    (
      <ScreenWrapper statusBarColor={colors?.prussianBlue}>
        <HeaderWellnessPlan navigation={navigation} />

        <ScrollView
          style={styles?.container}
          contentContainerStyle={styles?.contentContainerStyle}
        >
          <UserInfo BasicInfoData={basicInfoData} />
          {isData && (
            <WellnessOverviewCard
              activitiesData={wellnessPlanData?.wellnessActivity}
              primaryGoalsData={
                wellnessPlanData?.wellnessGoal[0]?.wellnessGoal_Primary
              }
              secondaryGoalsData={
                wellnessPlanData?.wellnessGoal?.[0]?.wellnessGoal_Secondary
              }
            />
          )}
          <ButtonsBtm navigation={navigation} />
        </ScrollView>
        {isLoading && <CommonLoader />}
        {/* {isLoading&& <LoaderSurf/>} */}
      </ScreenWrapper>
    )
  );
};
export default WellnessGoal;
