export default {
  POST_CREATEDEVICE_REQUEST: "POST_CREATEDEVICE_REQUEST",
  POST_CREATEDEVICE_SUCCESS: "POST_CREATEDEVICE_SUCCESS",
  POST_CREATEDEVICE_FAILURE: "POST_CREATEDEVICE_FAILURE",

  POST_CREATEHEALTHDATA_REQUEST: "POST_CREATEHEALTHDATA_REQUEST",
  POST_CREATEHEALTHDATA_SUCCESS: "POST_CREATEHEALTHDATA_SUCCESS",
  POST_CREATEHEALTHDATA_FAILURE: "POST_CREATEHEALTHDATA_FAILURE",

  POST_CREATE_VITAL_SMANUALLY_REQUEST: "POST_CREATE_VITAL_SMANUALLY_REQUEST",
  POST_CREATE_VITAL_SMANUALLY_SUCCESS: "POST_CREATE_VITAL_SMANUALLY_SUCCESS",
  POST_CREATE_VITAL_SMANUALLY_FAILURE: "POST_CREATE_VITAL_SMANUALLY_FAILURE",

  POST_GETVITALSACTIVITYSTATUSSUMMARY_REQUEST:
    "POST_GETVITALSACTIVITYSTATUSSUMMARY_REQUEST",
  POST_GETVITALSACTIVITYSTATUSSUMMARY_SUCCESS:
    "POST_GETVITALSACTIVITYSTATUSSUMMARY_SUCCESS",
  POST_GETVITALSACTIVITYSTATUSSUMMARY_FAILURE:
    "POST_GETVITALSACTIVITYSTATUSSUMMARY_FAILURE",

  GET_VITALS_ACTIVITY_STATUS_REQUEST: "GET_VITALS_ACTIVITY_STATUS_REQUEST",
  GET_VITALS_ACTIVITY_STATUS_SUCCESS: "GET_VITALS_ACTIVITY_STATUS_SUCCESS",
  GET_VITALS_ACTIVITY_STATUS_FAILURE: "GET_VITALS_ACTIVITY_STATUS_FAILURE",

  GET_VITAL_SUMMARY_REQUEST: "GET_VITAL_SUMMARY_REQUEST",
  GET_VITAL_SUMMARY_SUCCESS: "GET_VITAL_SUMMARY_SUCCESS",
  GET_VITAL_SUMMARY_FAILURE: "GET_VITAL_SUMMARY_FAILURE",
};
