export default {
  POST_CREATECOMMUNITY_PROFILE_REQUEST: "POST_CREATECOMMUNITY_PROFILE_REQUEST",
  POST_CREATECOMMUNITY_PROFILE_SUCCESS: "POST_CREATECOMMUNITY_PROFILE_SUCCESS",
  POST_CREATECOMMUNITY_PROFILE_FAILURE: "POST_CREATECOMMUNITY_PROFILE_FAILURE",

  POST_CREATE_FEED_REQUEST: "POST_CREATE_FEED_REQUEST",
  POST_CREATE_FEED_SUCCESS: "POST_CREATE_FEED_SUCCESS",
  POST_CREATE_FEED_FAILURE: "POST_CREATE_FEED_FAILURE",
  // createFeed

  POST_LIKE_FEED_REQUEST: "POST_LIKE_FEED_REQUEST",
  POST_LIKE_FEED_SUCCESS: "POST_LIKE_FEED_SUCCESS",
  POST_LIKE_FEED_FAILURE: "POST_LIKE_FEED_FAILURE", //SaveOrUnSaveFeed

  POST_COMMENT_FEED_REQUEST: "POST_COMMENT_FEED_REQUEST",
  POST_COMMENT_FEED_SUCCESS: "POST_COMMENT_FEED_SUCCESS",
  POST_COMMENT_FEED_FAILURE: "POST_COMMENT_FEED_FAILURE",

  POST_COMMENT_REPLY_REQUEST: "POST_COMMENT_REPLY_REQUEST",
  POST_COMMENT_REPLY_SUCCESS: "POST_COMMENT_REPLY_SUCCESS",
  POST_COMMENT_REPLY_FAILURE: "POST_COMMENT_REPLY_FAILURE",
  //DELETE_COMMENTS_OR_REPLY
  DELETE_COMMENTS_OR_REPLY_REQUEST: "DELETE_COMMENTS_OR_REPLY_REQUEST",
  DELETE_COMMENTS_OR_REPLY_SUCCESS: "DELETE_COMMENTS_OR_REPLY_SUCCESS",
  DELETE_COMMENTS_OR_REPLY_FAILURE: "DELETE_COMMENTS_OR_REPLY_FAILURE",

  POST_CREATE_GROUP_REQUEST: "POST_CREATE_GROUP_REQUEST",
  POST_CREATE_GROUP_SUCCESS: "POST_CREATE_GROUP_SUCCESS",
  POST_CREATE_GROUP_FAILURE: "POST_CREATE_GROUP_FAILURE",

  PUT_UPDATE_GROUP_REQUEST: "PUT_UPDATE_GROUP_REQUEST",
  PUT_UPDATE_GROUP_SUCCESS: "PUT_UPDATE_GROUP_SUCCESS",
  PUT_UPDATE_GROUP_FAILURE: "PUT_UPDATE_GROUP_FAILURE",

  PUT_UPDATE_FEED_REQUEST: "PUT_UPDATE_FEED_REQUEST",
  PUT_UPDATE_FEED_SUCCESS: "PUT_UPDATE_FEED_SUCCESS",
  PUT_UPDATE_FEED_FAILURE: "PUT_UPDATE_FEED_FAILURE",

  POST_CREATE_OR_JOINED_GROUP_REQUEST: "POST_CREATE_OR_JOINED_GROUP_REQUEST",
  POST_CREATE_OR_JOINED_GROUP_SUCCESS: "POST_CREATE_OR_JOINED_GROUP_SUCCESS",
  POST_CREATE_OR_JOINED_GROUP_FAILURE: "POST_CREATE_OR_JOINED_GROUP_FAILURE",

  POST_PRIVATEANDPUBLICGROUPLIST_REQUEST:
    "POST_PRIVATEANDPUBLICGROUPLIST_REQUEST",
  POST_PRIVATEANDPUBLICGROUPLIST_SUCCESS:
    "POST_PRIVATEANDPUBLICGROUPLIST_SUCCESS",
  POST_PRIVATEANDPUBLICGROUPLIST_FAILURE:
    "POST_PRIVATEANDPUBLICGROUPLIST_FAILURE",

  POST_CREATECONNECTION_REQUEST: "POST_CREATECONNECTION_REQUEST",
  POST_CREATECONNECTION_SUCCESS: "POST_CREATECONNECTION_SUCCESS",
  POST_CREATECONNECTION_FAILURE: "POST_CREATECONNECTION_FAILURE",

  POST_JOIN_GROUP_REQUEST: "POST_JOIN_GROUP_REQUEST",
  POST_JOIN_GROUP_SUCCESS: "POST_JOIN_GROUP_SUCCESS",
  POST_JOIN_GROUP_FAILURE: "POST_JOIN_GROUP_FAILURE", //InsertGlobalCodeAPI

  POST_ADD_GROUP_MEMBERS_REQUEST: "POST_ADD_GROUP_MEMBERS_REQUEST",
  POST_ADD_GROUP_MEMBERS_SUCCESS: "POST_ADD_GROUP_MEMBERS_SUCCESS",
  POST_ADD_GROUP_MEMBERS_FAILURE: "POST_ADD_GROUP_MEMBERS_FAILURE",

  POST_SHAREFEED_REQUEST: "POST_SHAREFEED_REQUEST",
  POST_SHAREFEED_SUCCESS: "POST_SHAREFEED_SUCCESS",
  POST_SHAREFEED_FAILURE: "POST_SHAREFEED_FAILURE",

  // addGroupMember

  GET_GROUP_DETAILS_BY_ID_REQUEST: "GET_GROUP_DETAILS_BY_ID_REQUEST",
  GET_GROUP_DETAILS_BY_ID_SUCCESS: "GET_GROUP_DETAILS_BY_ID_SUCCESS",
  GET_GROUP_DETAILS_BY_ID_FAILURE: "GET_GROUP_DETAILS_BY_ID_FAILURE",

  GET_CHAT_REQUEST: "GET_CHAT_REQUEST",
  GET_CHAT_SUCCESS: "GET_CHAT_SUCCESS",
  GET_CHAT_FAILURE: "GET_CHAT_FAILURE",

  GET_COMMENT_AND_REPLIES_BYFEED_ID_REQUEST:
    "GET_COMMENT_AND_REPLIES_BYFEED_ID_REQUEST",
  GET_COMMENT_AND_REPLIES_BYFEED_ID_SUCCESS:
    "GET_COMMENT_AND_REPLIES_BYFEED_ID_SUCCESS",
  GET_COMMENT_AND_REPLIES_BYFEED_ID_FAILURE:
    "GET_COMMENT_AND_REPLIES_BYFEED_ID_FAILURE",

  GET_FEEDS_BY_GROUP_ID_REQUEST: "GET_FEEDS_BY_GROUP_ID_REQUEST",
  GET_FEEDS_BY_GROUP_ID_SUCCESS: "GET_FEEDS_BY_GROUP_ID_SUCCESS",
  GET_FEEDS_BY_GROUP_ID_FAILURE: "GET_FEEDS_BY_GROUP_ID_FAILURE",

  GET_SUGGESTED_GROUPS_REQUEST: "GET_SUGGESTED_GROUPS_REQUEST",
  GET_SUGGESTED_GROUPS_SUCCESS: "GET_SUGGESTED_GROUPS_SUCCESS",
  GET_SUGGESTED_GROUPS_FAILURE: "GET_SUGGESTED_GROUPS_FAILURE",

  GET_TRENDINGFEEDS_REQUEST: "GET_TRENDINGFEEDS_REQUEST",
  GET_TRENDINGFEEDS_SUCCESS: "GET_TRENDINGFEEDS_SUCCESS",
  GET_TRENDINGFEEDS_FAILURE: "GET_TRENDINGFEEDS_FAILURE",
  //SAVEDFEEDSLIST
  GET_SAVEDFEEDSLIST_REQUEST: "GET_SAVEDFEEDSLIST_REQUEST",
  GET_SAVEDFEEDSLIST_SUCCESS: "GET_SAVEDFEEDSLIST_SUCCESS",
  GET_SAVEDFEEDSLIST_FAILURE: "GET_SAVEDFEEDSLIST_FAILURE",

  GET_FEEDBY_ID_REQUEST: "GET_FEEDBY_ID_REQUEST",
  GET_FEEDBY_ID_SUCCESS: "GET_FEEDBY_ID_SUCCESS",
  GET_FEEDBY_ID_FAILURE: "GET_FEEDBY_ID_FAILURE",

  PUT_UPDATECOMMUNITYPROFILE_REQUEST: "PUT_UPDATECOMMUNITYPROFILE_REQUEST",
  PUT_UPDATECOMMUNITYPROFILE_SUCCESS: "PUT_UPDATECOMMUNITYPROFILE_SUCCESS",
  PUT_UPDATECOMMUNITYPROFILE_FAILURE: "PUT_UPDATECOMMUNITYPROFILE_FAILURE",

  PUT_ACCEPTORREJECT_INVITE_REQUEST: "PUT_ACCEPTORREJECT_INVITE_REQUEST",
  PUT_ACCEPTORREJECT_INVITE_SUCCESS: "PUT_ACCEPTORREJECT_INVITE_SUCCESS",
  PUT_ACCEPTORREJECT_INVITE_FAILURE: "PUT_ACCEPTORREJECT_INVITE_FAILURE",

  PUT_ACCEPTORREJECT_CONNECTIONREQUEST_REQUEST:
    "PUT_ACCEPTORREJECT_CONNECTIONREQUEST_REQUEST",
  PUT_ACCEPTORREJECT_CONNECTIONREQUEST_SUCCESS:
    "PUT_ACCEPTORREJECT_CONNECTIONREQUEST_SUCCESS",
  PUT_ACCEPTORREJECT_CONNECTIONREQUEST_FAILURE:
    "PUT_ACCEPTORREJECT_CONNECTIONREQUEST_FAILURE",

  // AcceptOrRejectConnectionRequest

  GET_GLOBALJSONBY_CATEGORYNAME_REQUEST:
    "GET_GLOBALJSONBY_CATEGORYNAME_REQUEST",
  GET_GLOBALJSONBY_CATEGORYNAME_SUCCESS:
    "GET_GLOBALJSONBY_CATEGORYNAME_SUCCESS",
  GET_GLOBALJSONBY_CATEGORYNAME_FAILURE:
    "GET_GLOBALJSONBY_CATEGORYNAME_FAILURE",

  GET_COMMUNITYPROFILE_REQUEST: "GET_COMMUNITYPROFILE_REQUEST",
  GET_COMMUNITYPROFILE_SUCCESS: "GET_COMMUNITYPROFILE_SUCCESS",
  GET_COMMUNITYPROFILE_FAILURE: "GET_COMMUNITYPROFILE_FAILURE",

  GET_COMMUNITYUSERLIST_REQUEST: "GET_COMMUNITYUSERLIST_REQUEST",
  GET_COMMUNITYUSERLIST_SUCCESS: "GET_COMMUNITYUSERLIST_SUCCESS",
  GET_COMMUNITYUSERLIST_FAILURE: "GET_COMMUNITYUSERLIST_FAILURE",

  POST_CONNECTEDUSERLIST_REQUEST: "POST_CONNECTEDUSERLIST_REQUEST",
  POST_CONNECTEDUSERLIST_SUCCESS: "POST_CONNECTEDUSERLIST_SUCCESS",
  POST_CONNECTEDUSERLIST_FAILURE: "POST_CONNECTEDUSERLIST_FAILURE",

  POST_FEED_REPORT_REQUEST: "POST_FEED_REPORT_REQUEST",
  POST_FEED_REPORT_SUCCESS: "POST_FEED_REPORT_SUCCESS",
  POST_FEED_REPORT_FAILURE: "POST_FEED_REPORT_FAILURE",

  //

  GET_MEMBERSBYGROUPID_REQUEST: "GET_MEMBERSBYGROUPID_REQUEST",
  GET_MEMBERSBYGROUPID_SUCCESS: "GET_MEMBERSBYGROUPID_SUCCESS",
  GET_MEMBERSBYGROUPID_FAILURE: "GET_MEMBERSBYGROUPID_FAILURE",

  DELETE_LEAVE_GROUP_REQUEST: "DELETE_LEAVE_GROUP_REQUEST",
  DELETE_LEAVE_GROUP_SUCCESS: "DELETE_LEAVE_GROUP_SUCCESS",
  DELETE_LEAVE_GROUP_FAILURE: "DELETE_LEAVE_GROUP_FAILURE",

  DELETE_REMOVEJOINREQUEST_REQUEST: "DELETE_REMOVEJOINREQUEST_REQUEST",
  DELETE_REMOVEJOINREQUEST_SUCCESS: "DELETE_REMOVEJOINREQUEST_SUCCESS",
  DELETE_REMOVEJOINREQUEST_FAILURE: "DELETE_REMOVEJOINREQUEST_FAILURE",

  DELETE_FEED_REQUEST: "DELETE_FEED_REQUEST",
  DELETE_FEED_SUCCESS: "DELETE_FEED_SUCCESS",
  DELETE_FEED_FAILURE: "DELETE_FEED_FAILURE",

  DELETE_GROUP_REQUEST: "DELETE_GROUP_REQUEST",
  DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
  DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE", //SearchAny

  DELETE_REMOVE_GROUP_MEMBERS_REQUEST: "DELETE_REMOVE_GROUP_MEMBERS_REQUEST",
  DELETE_REMOVE_GROUP_MEMBERS_SUCCESS: "DELETE_REMOVE_GROUP_MEMBERS_SUCCESS",
  DELETE_REMOVE_GROUP_MEMBERS_FAILURE: "DELETE_REMOVE_GROUP_MEMBERS_FAILURE",

  // Redux save data

  SELECTEDGROUPMEMBERS_REQUEST: "SELECTEDGROUPMEMBERS_REQUEST",
  PROFILEDETAILSCOMMUNITY_REQUEST: "PROFILEDETAILSCOMMUNITY_REQUEST",
  PROFILEDETAILSCOMMUNITY_SUCCESS: "PROFILEDETAILSCOMMUNITY_SUCCESS",

  INSERTGLOBALCODE_REQUEST: "INSERTGLOBALCODE_REQUEST",
  INSERTGLOBALCODE_SUCCESS: "INSERTGLOBALCODE_SUCCESS",
  INSERTGLOBALCODE_FAILURE: "INSERTGLOBALCODE_FAILURE", //INSERTGLOBALCODEAPI

  SAVEORUNSAVEFEED_REQUEST: "SAVEORUNSAVEFEED_REQUEST",
  SAVEORUNSAVEFEED_SUCCESS: "SAVEORUNSAVEFEED_SUCCESS",
  SAVEORUNSAVEFEED_FAILURE: "SAVEORUNSAVEFEED_FAILURE", //SAVEORUNSAVEFEED

  SEARCH_ANY_REQUEST: "SEARCH_ANY_REQUEST",
  SEARCH_ANY_SUCCESS: "SEARCH_ANY_SUCCESS",
  SEARCH_ANY_FAILURE: "SEARCH_ANY_FAILURE", //SEARCH_ANY

  USER_NOT_FOUND: "USER_NOT_FOUND",
};
