export default {
  // POST_CREATEDEVICE_REQUEST: "POST_CREATEDEVICE_REQUEST",
  // POST_CREATEDEVICE_SUCCESS: "POST_CREATEDEVICE_SUCCESS",
  // POST_CREATEDEVICE_FAILURE: "POST_CREATEDEVICE_FAILURE",

  GET_MOODTRACKING_QUESTION_REQUEST: "GET_MOODTRACKING_QUESTION_REQUEST",
  GET_MOODTRACKING_QUESTION_SUCCESS: "GET_MOODTRACKING_QUESTION_SUCCESS",
  GET_MOODTRACKING_QUESTION_FAILURE: "GET_MOODTRACKING_QUESTION_FAILURE",

  SAVE_MOODTRACKING_QUESTION_REQUEST: "SAVE_MOODTRACKING_QUESTION_REQUEST",
  SAVE_MOODTRACKING_QUESTION_SUCCESS: "SAVE_MOODTRACKING_QUESTION_SUCCESS",
  SAVE_MOODTRACKING_QUESTION_FAILURE: "SAVE_MOODTRACKING_QUESTION_FAILURE",
  //GetMoodTrackingDetails
  GET_MOODTRACKING_DETAILS_REQUEST: "GET_MOODTRACKING_DETAILS_REQUEST",
  GET_MOODTRACKING_DETAILS_SUCCESS: "GET_MOODTRACKING_DETAILS_SUCCESS",
  GET_MOODTRACKING_DETAILS_FAILURE: "GET_MOODTRACKING_DETAILS_FAILURE",

  GET_GENERATEONBOARDINGDETAILS_REQUEST:
    "GET_GENERATEONBOARDINGDETAILS_REQUEST",
  GET_GENERATEONBOARDINGDETAILS_SUCCESS:
    "GET_GENERATEONBOARDINGDETAILS_SUCCESS",
  GET_GENERATEONBOARDINGDETAILS_FAILURE:
    "GET_GENERATEONBOARDINGDETAILS_FAILURE",

  GET_QOUTES_REQUEST: "GET_QOUTES_REQUEST",
  GET__QOUTES_SUCCESS: "GET__QOUTES_SUCCESS",
  GET__QOUTES_FAILURE: "GET__QOUTES_FAILURE",
  //GetReplaceCategoryQuestionsByName
  GETREPLACECATEGORYQUESTIONSBYNAME_REQUEST:
    "GETREPLACECATEGORYQUESTIONSBYNAME_REQUEST",
  GETREPLACECATEGORYQUESTIONSBYNAME_SUCCESS:
    "GETREPLACECATEGORYQUESTIONSBYNAME_SUCCESS",
  GETREPLACECATEGORYQUESTIONSBYNAME_FAILURE:
    "GETREPLACECATEGORYQUESTIONSBYNAME_FAILURE",

  GET_MOODJOURNALING_QUESTION_REQUEST: "GET_MOODJOURNALING_QUESTION_REQUEST",
  GET_MOODJOURNALING_QUESTION_SUCCESS: "GET_MOODJOURNALING_QUESTION_SUCCESS",
  GET_MOODJOURNALING_QUESTION_FAILURE: "GET_MOODJOURNALING_QUESTION_FAILURE",

  POST_SAVEMOODJOURNALING_QUESTION_REQUEST:
    "POST_SAVEMOODJOURNALING_QUESTION_REQUEST",
  POST_SAVEMOODJOURNALING_QUESTION_SUCCESS:
    "POST_SAVEMOODJOURNALING_QUESTION_SUCCESS",
  POST_SAVEMOODJOURNALING_QUESTION_FAILURE:
    "POST_SAVEMOODJOURNALING_QUESTION_FAILURE",

  GET_MOODJOUTNALING_DETAILS_REQUEST: "GET_MOODJOUTNALING_DETAILS_REQUEST",
  GET_MOODJOUTNALING_DETAILS_SUCCESS: "GET_MOODJOUTNALING_DETAILS_SUCCESS",
  GET_MOODJOUTNALING_DETAILS_FAILURE: "GET_MOODJOUTNALING_DETAILS_FAILURE",

  GET_WELLNESS_OVERVIEW_REQUEST: "GET_WELLNESS_OVERVIEW_REQUEST",
  GET_WELLNESS_OVERVIEW_SUCCESS: "GET_WELLNESS_OVERVIEW_SUCCESS",
  GET_WELLNESS_OVERVIEW_FAILURE: "GET_WELLNESS_OVERVIEW_FAILURE",

  GET_GETMOBILEDASHBOARDPROMPTS_REQUEST:
    "GET_GETMOBILEDASHBOARDPROMPTS_REQUEST",
  GET_GETMOBILEDASHBOARDPROMPTS_SUCCESS:
    "GET_GETMOBILEDASHBOARDPROMPTS_SUCCESS",
  GET_GETMOBILEDASHBOARDPROMPTS_FAILURE:
    "GET_GETMOBILEDASHBOARDPROMPTS_FAILURE",

  GET_GETGOALSGRAPHDATABYDATE_REQUEST: "GET_GETGOALSGRAPHDATABYDATE_REQUEST",
  GET_GETGOALSGRAPHDATABYDATE_SUCCESS: "GET_GETGOALSGRAPHDATABYDATE_SUCCESS",
  GET_GETGOALSGRAPHDATABYDATE_FAILURE: "GET_GETGOALSGRAPHDATABYDATE_FAILURE",

  GET_GETACTIVITIESGRAPHDATEBYDATE_REQUEST:
    "GET_GETACTIVITIESGRAPHDATEBYDATE_REQUEST",
  GET_GETACTIVITIESGRAPHDATEBYDATE_SUCCESS:
    "GET_GETACTIVITIESGRAPHDATEBYDATE_SUCCESS",
  GET_GETACTIVITIESGRAPHDATEBYDATE_FAILURE:
    "GET_GETACTIVITIESGRAPHDATEBYDATE_FAILURE",

  GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_REQUEST:
    "GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_REQUEST",
  GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_SUCCESS:
    "GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_SUCCESS",
  GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_FAILURE:
    "GET_GETUSERMISSINGPROFILEDATAPOINTQUESTIONS_FAILURE",

  POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_REQUEST:
    "POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_REQUEST",
  POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_SUCCESS:
    "POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_SUCCESS",
  POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_FAILURE:
    "POST_SAVEUSERMISSINGPROFILEDATAPOINTANSWERSS_FAILURE",

  GET_USER_INDIVIDUAL_GOALS_LIST_REQUEST:
    "GET_USER_INDIVIDUAL_GOALS_LIST_REQUEST",
  GET_USER_INDIVIDUAL_GOALS_LIST_SUCCESS:
    "GET_USER_INDIVIDUAL_GOALS_LIST_SUCCESS",
  GET_USER_INDIVIDUAL_GOALS_LIST_FAILURE:
    "GET_USER_INDIVIDUAL_GOALS_LIST_FAILURE",

  GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_REQUEST:
    "GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_REQUEST",
  GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_SUCCESS:
    "GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_SUCCESS",
  GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_FAILURE:
    "GET_GETUSERMOBILEDASHBOARDQUOTESBYDATE_FAILURE",

  GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_REQUEST:
    "GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_REQUEST",
  GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_SUCCESS:
    "GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_SUCCESS",
  GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_FAILURE:
    "GET_ACTIVITIES_QUESTIONS_BY_CATEGORYID_FAILURE",
  //DELETE_ACTIVITY_BY_ID
  DELETE_ACTIVITY_BY_ID_REQUEST: "DELETE_ACTIVITY_BY_ID_REQUEST",
  DELETE_ACTIVITY_BY_ID_SUCCESS: "DELETE_ACTIVITY_BY_ID_SUCCESS",
  DELETE_ACTIVITY_BY_ID_FAILURE: "DELETE_ACTIVITY_BY_ID_FAILURE",

  DELETEGOALBYID_REQUEST: "DELETEGOALBYID_REQUEST",
  DELETEGOALBYID_SUCCESS: "DELETEGOALBYID_SUCCESS",
  DELETEGOALBYID_FAILURE: "DELETEGOALBYID_FAILURE",
  // GETUSERACTIVITYAVAILABILITY
  GETUSERACTIVITYAVAILABILITY_REQUEST: "GETUSERACTIVITYAVAILABILITY_REQUEST",
  GETUSERACTIVITYAVAILABILITY_SUCCESS: "GETUSERACTIVITYAVAILABILITY_SUCCESS",
  GETUSERACTIVITYAVAILABILITY_FAILURE: "GETUSERACTIVITYAVAILABILITY_FAILURE",
  //GETUSERSCHEDULEDACTIVITIESLIST
  GETUSERSCHEDULEDACTIVITIESLIST_REQUEST:
    "GETUSERSCHEDULEDACTIVITIESLIST_REQUEST",
  GETUSERSCHEDULEDACTIVITIESLIST_SUCCESS:
    "GETUSERSCHEDULEDACTIVITIESLIST_SUCCESS",
  GETUSERSCHEDULEDACTIVITIESLIST_FAILURE:
    "GETUSERSCHEDULEDACTIVITIESLIST_FAILURE",
  //UPDATE_ACTIVITY_SCHEDULE_TIME
  UPDATE_ACTIVITY_SCHEDULE_TIME_REQUEST:
    "UPDATE_ACTIVITY_SCHEDULE_TIME_REQUEST",
  UPDATE_ACTIVITY_SCHEDULE_TIME_SUCCESS:
    "UPDATE_ACTIVITY_SCHEDULE_TIME_SUCCESS",
  UPDATE_ACTIVITY_SCHEDULE_TIME_FAILURE:
    "UPDATE_ACTIVITY_SCHEDULE_TIME_FAILURE", //RegenerateWellnessDetailsById

  //GETEDITABLEACTIVITYQUESTIONSBYID
  GETEDITABLEACTIVITYQUESTIONSBYID_REQUEST:
    "GETEDITABLEACTIVITYQUESTIONSBYID_REQUEST",
  GETEDITABLEACTIVITYQUESTIONSBYID_SUCCESS:
    "GETEDITABLEACTIVITYQUESTIONSBYID_SUCCESS",
  GETEDITABLEACTIVITYQUESTIONSBYID_FAILURE:
    "GETEDITABLEACTIVITYQUESTIONSBYID_FAILURE",
  EDITACTIVITYDETAILSBYID_REQUEST: "EDITACTIVITYDETAILSBYID_REQUEST",
  EDITACTIVITYDETAILSBYID_SUCCESS: "EDITACTIVITYDETAILSBYID_SUCCESS",
  EDITACTIVITYDETAILSBYID_FAILURE: "EDITACTIVITYDETAILSBYID_FAILURE",
  //EDITGOALDETAILSBYID
  EDITGOALDETAILSBYID_REQUEST: "EDITGOALDETAILSBYID_REQUEST",
  EDITGOALDETAILSBYID_SUCCESS: "EDITGOALDETAILSBYID_SUCCESS",
  EDITGOALDETAILSBYID_FAILURE: "EDITGOALDETAILSBYID_FAILURE",
  REPLACEACTIVITYDETAILSBYID_REQUEST: "REPLACEACTIVITYDETAILSBYID_REQUEST",
  REPLACEACTIVITYDETAILSBYID_SUCCESS: "REPLACEACTIVITYDETAILSBYID_SUCCESS",
  REPLACEACTIVITYDETAILSBYID_FAILURE: "REPLACEACTIVITYDETAILSBYID_FAILURE",
  //GETEDITABLEGOALQUESTIONSBYID
  GETEDITABLEGOALQUESTIONSBYID_REQUEST: "GETEDITABLEGOALQUESTIONSBYID_REQUEST",
  GETEDITABLEGOALQUESTIONSBYID_SUCCESS: "GETEDITABLEGOALQUESTIONSBYID_SUCCESS",
  GETEDITABLEGOALQUESTIONSBYID_FAILURE: "GETEDITABLEGOALQUESTIONSBYID_FAILURE",
  //REPLACEGOALDETAILSBYID
  REPLACEGOALDETAILSBYID_REQUEST: "REPLACEGOALDETAILSBYID_REQUEST",
  REPLACEGOALDETAILSBYID_SUCCESS: "REPLACEGOALDETAILSBYID_SUCCESS",
  REPLACEGOALDETAILSBYID_FAILURE: "REPLACEGOALDETAILSBYID_FAILURE",

  POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_REQUEST:
    "POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_REQUEST",
  POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_SUCCESS:
    "POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_SUCCESS",
  POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_FAILURE:
    "POST_AIDYNAMICPROMPTINGTOMOODJOURNALANDTRACKING_FAILURE",
  SAVETEMPORARYSLOTDATA: "SAVETEMPORARYSLOTDATA",
  SAVECURRENTSUGGESTIONSSCHEDULETIMEDATA:
    "SAVECURRENTSUGGESTIONSSCHEDULETIMEDATA",

  //REPLACEACTIVITYDETAILSBYID
  REGENERATE_WELLNESSDETAILSBYID_REQUEST:
    "REGENERATE_WELLNESSDETAILSBYID_REQUEST",
  REGENERATE_WELLNESSDETAILSBYID_SUCCESS:
    "REGENERATE_WELLNESSDETAILSBYID_SUCCESS",
  REGENERATE_WELLNESSDETAILSBYID_FAILURE:
    "REGENERATE_WELLNESSDETAILSBYID_FAILURE", //
};
