export default {
  GET_ALLGLOBALCODES_WITHCATEGORY_REQUEST:
    "GET_ALLGLOBALCODES_WITHCATEGORY_REQUEST",
  GET_ALLGLOBALCODES_WITHCATEGORY_SUCCESS:
    "GET_ALLGLOBALCODES_WITHCATEGORY_SUCCESS",
  GET_ALLGLOBALCODES_WITHCATEGORY_FAILURE:
    "GET_ALLGLOBALCODES_WITHCATEGORY_FAILURE",
};
