export default {
    GET_GETGLOBALCODESBYCATEGORYNAME_REQUEST: "GET_GETGLOBALCODESBYCATEGORYNAME_REQUEST",
    GET_GETGLOBALCODESBYCATEGORYNAME_SUCCESS: "GET_GETGLOBALCODESBYCATEGORYNAME_SUCCESS",
    GET_GETGLOBALCODESBYCATEGORYNAME_FAILURE: "GET_GETGLOBALCODESBYCATEGORYNAME_FAILURE",
}