export default {
  POST_TOKEN_REQUEST: "POST_TOKEN_REQUEST",
  POST_TOKEN_SUCCESS: "POST_TOKEN_SUCCESS",
  POST_TOKEN_FAILURE: "POST_TOKEN_FAILURE",

  POST_LOGIN_EMAIL_REQUEST: "POST_LOGIN_EMAIL_REQUEST",
  POST_LOGIN_EMAIL_SUCCESS: "POST_LOGIN_EMAIL_SUCCESS",
  POST_LOGIN_EMAIL_FAILURE: "POST_LOGIN_EMAIL_FAILURE",

  POST_OTP_VERIFY_REQUEST: "POST_OTP_VERIFY_REQUEST",
  POST_OTP_VERIFY_SUCCESS: "POST_OTP_VERIFY_SUCCESS",
  POST_OTP_VERIFY_FAILURE: "POST_OTP_VERIFY_FAILURE",

  POST_REGISTER_REQUEST: "POST_REGISTER_REQUEST",
  POST_REGISTER_SUCCESS: "POST_REGISTER_SUCCESS",
  POST_REGISTER_FAILURE: "POST_REGISTER_FAILURE",

  POST_VERIFYFORGOTPASSWORDOTP_REQUEST: "POST_VERIFYFORGOTPASSWORDOTP_REQUEST",
  POST_VERIFYFORGOTPASSWORDOTP_SUCCESS: "POST_VERIFYFORGOTPASSWORDOTP_SUCCESS",
  POST_VERIFYFORGOTPASSWORDOTP_FAILURE: "POST_VERIFYFORGOTPASSWORDOTP_FAILURE",

  POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_REQUEST:
    "POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_REQUEST",
  POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_SUCCESS:
    "POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_SUCCESS",
  POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_FAILURE:
    "POST_RESENDOTP_SIGNUPWITHEMAILANDPHONE_FAILURE",

  POST_RESENDOTP_LOGINWITHPHONE_REQUEST:
    "POST_RESENDOTP_LOGINWITHPHONE_REQUEST",
  POST_RESENDOTP_LOGINWITHPHONE_SUCCESS:
    "POST_RESENDOTP_LOGINWITHPHONE_SUCCESS",
  POST_RESENDOTP_LOGINWITHPHONE_FAILURE:
    "POST_RESENDOTP_LOGINWITHPHONE_FAILURE",

  POST_RESENDOTP_FORGOTPASSWORD_REQUEST:
    "POST_RESENDOTP_FORGOTPASSWORD_REQUEST",
  POST_RESENDOTP_FORGOTPASSWORD_SUCCESS:
    "POST_RESENDOTP_FORGOTPASSWORD_SUCCESS",
  POST_RESENDOTP_FORGOTPASSWORD_FAILURE:
    "POST_RESENDOTP_FORGOTPASSWORD_FAILURE",

  POST_SIGN_OUT_REQUEST: "POST_SIGN_OUT_REQUEST",
  POST_SIGN_OUT_SUCCESS: "POST_SIGN_OUT_SUCCESS",
  POST_SIGN_OUT_FAILURE: "POST_SIGN_OUT_FAILURE",

  POST_DELETEUSER_REQUEST: "POST_DELETEUSER_REQUEST",
  POST_DELETEUSER_SUCCESS: "POST_DELETEUSER_SUCCESS",
  POST_DELETEUSER_FAILURE: "POST_DELETEUSER_FAILURE",

  POST_VERIFYOTPAND_DELETEUSER_REQUEST: "POST_VERIFYOTPAND_DELETEUSER_REQUEST",
  POST_VERIFYOTPAND_DELETEUSER_SUCCESS: "POST_VERIFYOTPAND_DELETEUSER_SUCCESS",
  POST_VERIFYOTPAND_DELETEUSER_FAILURE: "POST_VERIFYOTPAND_DELETEUSER_FAILURE",
  // VerifyOtpAndDeleteUser

  POST_PHONE_VERIFYOTP_REQUEST: "POST_PHONE_VERIFYOTP_REQUEST",
  POST_PHONE_VERIFYOTP_SUCCESS: "POST_PHONE_VERIFYOTP_SUCCESS",
  POST_PHONE_VERIFYOTP_FAILURE: "POST_PHONE_VERIFYOTP_FAILURE",

  POST_RESETPASSWORD_REQUEST: "POST_RESETPASSWORD_REQUEST",
  POST_RESETPASSWORD_SUCCESS: "POST_RESETPASSWORD_SUCCESS",
  POST_RESETPASSWORD_FAILURE: "POST_RESETPASSWORD_FAILURE",

  POST_RESENDOTP_REQUEST: "POST_RESENDOTP_REQUEST",
  POST_RESENDOTP_SUCCESS: "POST_RESENDOTP_SUCCESS",
  POST_RESENDOTP_FAILURE: "POST_RESENDOTP_FAILURE",

  POST_LOGIN_WITH_GOOGLE_REQUEST: "POST_LOGIN_WITH_GOOGLE_REQUEST",
  POST_LOGIN_WITH_GOOGLE_SUCCESS: "POST_LOGIN_WITH_GOOGLE_SUCCESS",
  POST_LOGIN_WITH_GOOGLE_FAILURE: "POST_LOGIN_WITH_GOOGLE_FAILURE",

  POST_LOGIN_WITH_APPLE_REQUEST: "POST_LOGIN_WITH_APPLE_REQUEST",
  POST_LOGIN_WITH_APPLE_SUCCESS: "POST_LOGIN_WITH_APPLE_SUCCESS",
  POST_LOGIN_WITH_APPLE_FAILURE: "POST_LOGIN_WITH_APPLE_FAILURE",

  POST_FORGOT_PASSWORD_REQUEST: "POST_FORGOT_PASSWORD_REQUEST",
  POST_FORGOT_PASSWORD_SUCCESS: "POST_FORGOT_PASSWORD_SUCCESS",
  POST_FORGOT_PASSWORD_FAILURE: "POST_FORGOT_PASSWORD_FAILURE",

  POST_LOGIN_PHONE_REQUEST: "POST_LOGIN_PHONE_REQUEST",
  POST_LOGIN_PHONE_SUCCESS: "POST_LOGIN_PHONE_SUCCESS",
  POST_LOGIN_PHONE_FAILURE: "POST_LOGIN_PHONE_FAILURE",

  POST_SELF_SIGNUP_REQUEST: "POST_SELF_SIGNUP_REQUEST",
  POST_SELF_SIGNUP_SUCCESS: "POST_SELF_SIGNUP_SUCCESS",
  POST_SELF_SIGNUP_FAILURE: "POST_SELF_SIGNUP_FAILURE",

  POST_LOGOUT_REQUEST: "POST_LOGOUT_REQUEST",
  POST_LOGOUT_SUCCESS: "POST_LOGOUT_SUCCESS",
  POST_LOGOUT_FAILURE: "POST_LOGOUT_FAILURE",

  POST_USERTYPE_REQUEST: "POST_USERTYPE_REQUEST",
  POST_USERTYPE_SUCCESS: "POST_USERTYPE_SUCCESS",
  POST_USERTYPE_FAILURE: "POST_USERTYPE_FAILURE",

  GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_REQUEST:
    "GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_REQUEST",
  GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_SUCCESS:
    "GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_SUCCESS",
  GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_FAILURE:
    "GET_CLINICIAN_DETAILS_BY_SEEKEREMAIL_FAILURE",

  POST_GETINVITEDSEEKERDETAILS_REQUEST: "POST_GETINVITEDSEEKERDETAILS_REQUEST",
  POST_GETINVITEDSEEKERDETAILS_SUCCESS: "POST_GETINVITEDSEEKERDETAILS_SUCCESS",
  POST_GETINVITEDSEEKERDETAILS_FAILURE: "POST_GETINVITEDSEEKERDETAILS_FAILURE",

  POST_SAVEORUPDATESEEKERINFO_REQUEST: "POST_SAVEORUPDATESEEKERINFO_REQUEST",
  POST_SAVEORUPDATESEEKERINFO_SUCCESS: "POST_SAVEORUPDATESEEKERINFO_SUCCESS",
  POST_SAVEORUPDATESEEKERINFO_FAILURE: "POST_SAVEORUPDATESEEKERINFO_FAILURE",

  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_REQUEST:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_REQUEST",
  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_SUCCESS:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_SUCCESS",
  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_FAILURE:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_FAILURE",

  SEEKER_NAME_REQUEST: "SEEKER_NAME_REQUEST",
  SEEKER_NAME_SUCCESS: "SEEKER_NAME_SUCCESS",
  SEEKER_NAME_FAILURE: "SEEKER_NAME_FAILURE",

  GET_RESOURCELIBRARY_TEMPLATE_REQUEST: "GET_RESOURCELIBRARY_TEMPLATE_REQUEST",
  GET_RESOURCELIBRARY_TEMPLATE_SUCCESS: "GET_RESOURCELIBRARY_TEMPLATE_SUCCESS",
  GET_RESOURCELIBRARY_TEMPLATE_FAILURE: "GET_RESOURCELIBRARY_TEMPLATE_FAILURE",

  GET_ACTIVITIES_TEMPLATES_REQUEST: "GET_ACTIVITIES_TEMPLATES_REQUEST",
  GET_ACTIVITIES_TEMPLATES_SUCCESS: "GET_ACTIVITIES_TEMPLATES_SUCCESS",
  GET_ACTIVITIES_TEMPLATES_FAILURE: "GET_ACTIVITIES_TEMPLATES_FAILURE",

  POST_SAVEUSERPRIVACYPOLICEINFO_REQUEST:
    "POST_SAVEUSERPRIVACYPOLICEINFO_REQUEST",
  POST_SAVEUSERPRIVACYPOLICEINFO_SUCCESS:
    "POST_SAVEUSERPRIVACYPOLICEINFO_SUCCESS",
  POST_SAVEUSERPRIVACYPOLICEINFO_FAILURE:
    "POST_SAVEUSERPRIVACYPOLICEINFO_FAILURE",

  POST_SAVECONSENTFORM_REQUEST: "POST_SAVECONSENTFORM_REQUEST",
  POST_SAVECONSENTFORM_SUCCESS: "POST_SAVECONSENTFORM_SUCCESS",
  POST_SAVECONSENTFORM_FAILURE: "POST_SAVECONSENTFORM_FAILURE",

  POST_GETCONSENTFORMSTATUS_REQUEST: "POST_GETCONSENTFORMSTATUS_REQUEST",
  POST_GETCONSENTFORMSTATUS_SUCCESS: "POST_GETCONSENTFORMSTATUS_SUCCESS",
  POST_GETCONSENTFORMSTATUS_FAILURE: "POST_GETCONSENTFORMSTATUS_FAILURE",
};
