export default {
  GET_ALL_NOTIFICATIONS_REQUEST: "GET_ALL_NOTIFICATIONS_REQUEST",
  GET_ALL_NOTIFICATIONS_SUCCESS: "GET_ALL_NOTIFICATIONS_SUCCESS",
  GET_ALL_NOTIFICATIONS_FAILURE: "GET_ALL_NOTIFICATIONS_FAILURE",

  GET_COMMUNITY_ACTIVITES_REQUEST: "GET_COMMUNITY_ACTIVITES_REQUEST",
  GET_COMMUNITY_ACTIVITES_SUCCESS: "GET_COMMUNITY_ACTIVITES_SUCCESS",
  GET_COMMUNITY_ACTIVITES_FAILURE: "GET_COMMUNITY_ACTIVITES_FAILURE",

  //SAVE_NOTIFICATION
  GET_SAVE_NOTIFICATION_REQUEST: "GET_SAVE_NOTIFICATION_REQUEST",
  GET_SAVE_NOTIFICATION_SUCCESS: "GET_SAVE_NOTIFICATION_SUCCESS",
  GET_SAVE_NOTIFICATION_FAILURE: "GET_SAVE_NOTIFICATION_FAILURE",
  //UPDATE_NOTIFICATION_STATUS
  GET_UPDATE_NOTIFICATION_STATUS_REQUEST:
    "GET_UPDATE_NOTIFICATION_STATUS_REQUEST",
  GET_UPDATE_NOTIFICATION_STATUS_SUCCESS:
    "GET_UPDATE_NOTIFICATION_STATUS_SUCCESS",
  GET_UPDATE_NOTIFICATION_STATUS_FAILURE:
    "GET_UPDATE_NOTIFICATION_STATUS_FAILURE",
  //DELETENOTIFICATIONBYID
  DELETENOTIFICATIONBYID_REQUEST: "DELETENOTIFICATIONBYID_REQUEST",
  DELETENOTIFICATIONBYID_SUCCESS: "DELETENOTIFICATIONBYID_SUCCESS",
  DELETENOTIFICATIONBYID_FAILURE: "DELETENOTIFICATIONBYID_FAILURE",
};
