export default {
  POST_ONBOARDING_REQUEST: "POST_ONBOARDING_REQUEST",
  POST_ONBOARDING_SUCCESS: "POST_ONBOARDING_SUCCESS",
  POST_ONBOARDING_FAILURE: "POST_ONBOARDING_FAILURE",

  GET_CONSENT_FORM_REQUEST: "GET_CONSENT_FORM_REQUEST",
  GET_CONSENT_FORM_SUCCESS: "GET_CONSENT_FORM_SUCCESS",
  GET_CONSENT_FORM_FAILURE: "GET_CONSENT_FORM_FAILURE",

  GET_ON_BOARDING_STEPS_REQUEST: "GET_ON_BOARDING_STEPS_REQUEST",
  GET_ON_BOARDING_STEPS_SUCCESS: "GET_ON_BOARDING_STEPS_SUCCESS",
  GET_ON_BOARDING_STEPS_FAILURE: "GET_ON_BOARDING_STEPS_FAILURE",

  GET_ASPIRATIONS_REQUEST: "GET_ASPIRATIONS_REQUEST",
  GET_ASPIRATIONS_SUCCESS: "GET_ASPIRATIONS_SUCCESS",
  GET_ASPIRATIONS_FAILURE: "GET_ASPIRATIONS_FAILURE",

  GET_AREA_OF_INTERSETS_REQUEST: "GET_AREA_OF_INTERSETS_REQUEST",
  GET_AREA_OF_INTERSETS_SUCCESS: "GET_AREA_OF_INTERSETS_SUCCESS",
  GET_AREA_OF_INTERSETS_FAILURE: "GET_AREA_OF_INTERSETS_FAILURE",

  GET_WELLNESS_PLAN_REQUEST: "GET_WELLNESS_PLAN_REQUEST",
  GET_WELLNESS_PLAN_SUCCESS: "GET_WELLNESS_PLAN_SUCCESS",
  GET_WELLNESS_PLAN_FAILURE: "GET_WELLNESS_PLAN_FAILURE",

  GET_GETREGENEREATEWELLNESSPLANSTEPS_REQUEST:
    "GET_GETREGENEREATEWELLNESSPLANSTEPS_REQUEST",
  GET_GETREGENEREATEWELLNESSPLANSTEPS_SUCCESS:
    "GET_GETREGENEREATEWELLNESSPLANSTEPS_SUCCESS",
  GET_GETREGENEREATEWELLNESSPLANSTEPS_FAILURE:
    "GET_GETREGENEREATEWELLNESSPLANSTEPS_FAILURE",

  POST_REGENERATESEEKERWELLNESSPLAN_REQUEST:
    "POST_REGENERATESEEKERWELLNESSPLAN_REQUEST",
  POST_REGENERATESEEKERWELLNESSPLAN_SUCCESS:
    "POST_REGENERATESEEKERWELLNESSPLAN_SUCCESS",
  POST_REGENERATESEEKERWELLNESSPLAN_FAILURE:
    "POST_REGENERATESEEKERWELLNESSPLAN_FAILURE",

  POST_CREATEWELLNESSPLANDETAILS_REQUEST:
    "POST_CREATEWELLNESSPLANDETAILS_REQUEST",
  POST_CREATEWELLNESSPLANDETAILS_SUCCESS:
    "POST_CREATEWELLNESSPLANDETAILS_SUCCESS",
  POST_CREATEWELLNESSPLANDETAILS_FAILURE:
    "POST_CREATEWELLNESSPLANDETAILS_FAILURE",

  POST_GETCONSENTFORMBYTYPE_REQUEST: "POST_GETCONSENTFORMBYTYPE_REQUEST",
  POST_GETCONSENTFORMBYTYPE_SUCCESS: "POST_GETCONSENTFORMBYTYPE_SUCCESS",
  POST_GETCONSENTFORMBYTYPE_FAILURE: "POST_GETCONSENTFORMBYTYPE_FAILURE",

  POST_GENERATEONBOARDINGDETAILS_REQUEST:
    "POST_GENERATEONBOARDINGDETAILS_REQUEST",
  POST_GENERATEONBOARDINGDETAILS_SUCCESS:
    "POST_GENERATEONBOARDINGDETAILS_SUCCESS",
  POST_GENERATEONBOARDINGDETAILS_FAILURE:
    "POST_GENERATEONBOARDINGDETAILS_FAILURE",

  GET_REGENERATE_ONBOARDINGDETAILS_REQUEST:
    "GET_REGENERATE_ONBOARDINGDETAILS_REQUEST",
  GET_REGENERATE_ONBOARDINGDETAILS_SUCCESS:
    "GET_REGENERATE_ONBOARDINGDETAILS_SUCCESS",
  GET_REGENERATE_ONBOARDINGDETAILS_FAILURE:
    "GET_REGENERATE_ONBOARDINGDETAILS_FAILURE",

  POST_REGENRATEON_BORDING_DETAILS_REQUEST:
    "POST_REGENRATEON_BORDING_DETAILS_REQUEST",
  POST_REGENRATEON_BORDING_DETAILS_SUCCESS:
    "POST_REGENRATEON_BORDING_DETAILS_SUCCESS",
  POST_REGENRATEON_BORDING_DETAILS_FAILURE:
    "POST_REGENRATEON_BORDING_DETAILS_FAILURE",

  POST_CREATE_GOALS_REQUEST: "POST_CREATE_GOALS_REQUEST",
  POST_CREATE_GOALS_SUCCESS: "POST_CREATE_GOALS_SUCCESS",
  POST_CREATE_GOALS_FAILURE: "POST_CREATE_GOALS_FAILURE",

  POST_CREATE_ACTIVITIES_REQUEST: "POST_CREATE_ACTIVITIES_REQUEST",
  POST_CREATE_ACTIVITIES_SUCCESS: "POST_CREATE_ACTIVITIES_SUCCESS",
  POST_CREATE_ACTIVITIES_FAILURE: "POST_CREATE_ACTIVITIES_FAILURE",

  POST_SAVESEEKERPLANNEREXPLORERID_REQUEST:
    "POST_SAVESEEKERPLANNEREXPLORERID_REQUEST",
  POST_SAVESEEKERPLANNEREXPLORERID_SUCCESS:
    "POST_SAVESEEKERPLANNEREXPLORERID_SUCCESS",
  POST_SAVESEEKERPLANNEREXPLORERID_FAILURE:
    "POST_SAVESEEKERPLANNEREXPLORERID_FAILURE",

  POST_SAVEQUIZFROMAI_REQUEST: "POST_SAVEQUIZFROMAI_REQUEST",
  POST_SAVEQUIZFROMAI_SUCCESS: "POST_SAVEQUIZFROMAI_SUCCESS",
  POST_SAVEQUIZFROMAI_FAILURE: "POST_SAVEQUIZFROMAI_FAILURE",

  POST_CREATE_RECOMMENDATIONS_REQUEST: "POST_CREATE_RECOMMENDATIONS_REQUEST",
  POST_CREATE_RECOMMENDATIONS_SUCCESS: "POST_CREATE_RECOMMENDATIONS_SUCCESS",
  POST_CREATE_RECOMMENDATIONS_FAILURE: "POST_CREATE_RECOMMENDATIONS_FAILURE",

  //SAVE_USER_ACTIVITIES_FROM_TEMPLATE
  SAVE_USER_ACTIVITIES_FROM_TEMPLATE_REQUEST:
    "SAVE_USER_ACTIVITIES_FROM_TEMPLATE_REQUEST",
  SAVE_USER_ACTIVITIES_FROM_TEMPLATE_SUCCESS:
    "SAVE_USER_ACTIVITIES_FROM_TEMPLATE_SUCCESS",
  SAVE_USER_ACTIVITIES_FROM_TEMPLATE_FAILURE:
    "SAVE_USER_ACTIVITIES_FROM_TEMPLATE_FAILURE",

  SAVE_SHORT_TERM_GOAL_DATA: "SAVE_SHORT_TERM_GOAL_DATA",
  SAVE_LONG_TERM_GOAL_DATA: "SAVE_LONG_TERM_GOAL_DATA",

  SAVE_MEDICAL_CONDITIONS: "SAVE_MEDICAL_CONDITIONS",
  FITNESS_ACTIVITY: "FITNESS_ACTIVITY",
  SAVE_STRESSORS_TRIGGERS: "SAVE_STRESSORS_TRIGGERS",

  GET_ACTIVITIES_FEEDBACKSTEPS_REQUEST: "GET_ACTIVITIES_FEEDBACKSTEPS_REQUEST",
  GET_ACTIVITIES_FEEDBACKSTEPS_SUCCESS: "GET_ACTIVITIES_FEEDBACKSTEPS_SUCCESS",
  GET_ACTIVITIES_FEEDBACKSTEPS_FAILURE: "GET_ACTIVITIES_FEEDBACKSTEPS_FAILURE",

  POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_REQUEST:
    "POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_REQUEST",
  POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_SUCCESS:
    "POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_SUCCESS",
  POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_FAILURE:
    "POST_SAVEACTIVITESFEEDBACKSTEPS_ANSWER_FAILURE",
  GET_GETACTIVITYDETAILSBYID_REQUEST: "GET_GETACTIVITYDETAILSBYID_REQUEST",
  GET_GETACTIVITYDETAILSBYID_SUCCESS: "GET_GETACTIVITYDETAILSBYID_SUCCESS",
  GET_GETACTIVITYDETAILSBYID_FAILURE: "GET_GETACTIVITYDETAILSBYID_FAILURE",

  GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_REQUEST:
    "GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_REQUEST",
  GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_SUCCESS:
    "GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_SUCCESS",
  GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_FAILURE:
    "GET_GETACTIVITYRECOMMEDATIONDETAILSBYID_FAILURE",

  GET_SAVESELECTEDRECOMMENDATION_REQUEST:
    "GET_SAVESELECTEDRECOMMENDATION_REQUEST",
  GET_SAVESELECTEDRECOMMENDATION_SUCCESS:
    "GET_SAVESELECTEDRECOMMENDATION_SUCCESS",
  GET_SAVESELECTEDRECOMMENDATION_FAILURE:
    "GET_SAVESELECTEDRECOMMENDATION_FAILURE",

  GET_GETACTIVITYRECENTHISTORYBYDATEANDID_REQUEST:
    "GET_GETACTIVITYRECENTHISTORYBYDATEANDID_REQUEST",
  GET_GETACTIVITYRECENTHISTORYBYDATEANDID_SUCCESS:
    "GET_GETACTIVITYRECENTHISTORYBYDATEANDID_SUCCESS",
  GET_GETACTIVITYRECENTHISTORYBYDATEANDID_FAILURE:
    "GET_GETACTIVITYRECENTHISTORYBYDATEANDID_FAILURE",

  GET_SAVEACTIVITYHISTORYDETAILD_REQUEST:
    "GET_SAVEACTIVITYHISTORYDETAILD_REQUEST",
  GET_SAVEACTIVITYHISTORYDETAILD_SUCCESS:
    "GET_SAVEACTIVITYHISTORYDETAILD_SUCCESS",
  GET_SAVEACTIVITYHISTORYDETAILD_FAILURE:
    "GET_SAVEACTIVITYHISTORYDETAILD_FAILURE",

  GET_GETUSERPLANNERONBOARDINGRESPONSE_REQUEST:
    "GET_GETUSERPLANNERONBOARDINGRESPONSE_REQUEST",
  GET_GETUSERPLANNERONBOARDINGRESPONSE_SUCCESS:
    "GET_GETUSERPLANNERONBOARDINGRESPONSE_SUCCESS",
  GET_GETUSERPLANNERONBOARDINGRESPONSE_FAILURE:
    "GET_GETUSERPLANNERONBOARDINGRESPONSE_FAILURE",

  GET_GETACTIVITYDETAILSBYIDANDDATE_REQUEST:
    "GET_GETACTIVITYDETAILSBYIDANDDATE_REQUEST",
  GET_GETACTIVITYDETAILSBYIDANDDATE_SUCCESS:
    "GET_GETACTIVITYDETAILSBYIDANDDATE_SUCCESS",
  GET_GETACTIVITYDETAILSBYIDANDDATE_FAILURE:
    "GET_GETACTIVITYDETAILSBYIDANDDATE_FAILURE",

  GET_SAVEONBOARDINGEXPLORERSTEPS_REQUEST:
    "GET_SAVEONBOARDINGEXPLORERSTEPS_REQUEST",
  GET_SAVEONBOARDINGEXPLORERSTEPS_SUCCESS:
    "GET_SAVEONBOARDINGEXPLORERSTEPS_SUCCESS",
  GET_SAVEONBOARDINGEXPLORERSTEPS_FAILURE:
    "GET_SAVEONBOARDINGEXPLORERSTEPS_FAILURE",

  POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_REQUEST:
    "POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_REQUEST",
  POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_SUCCESS:
    "POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_SUCCESS",
  POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_FAILURE:
    "POST_DELETESELECTEDACTIVITIESFROMAIRESPONSE_FAILURE",

  DELETESELECTEDGOALSFROMAIRESPONSE_REQUEST:
    "DELETESELECTEDGOALSFROMAIRESPONSE_REQUEST",
  DELETESELECTEDGOALSFROMAIRESPONSE_SUCCESS:
    "DELETESELECTEDGOALSFROMAIRESPONSE_SUCCESS",
  DELETESELECTEDGOALSFROMAIRESPONSE_FAILURE:
    "DELETESELECTEDGOALSFROMAIRESPONSE_FAILURE",

  POST_REGENERATESELECTEDACTIVITIESDETAILS_REQUEST:
    "POST_REGENERATESELECTEDACTIVITIESDETAILS_REQUEST",
  POST_REGENERATESELECTEDACTIVITIESDETAILS_SUCCESS:
    "POST_REGENERATESELECTEDACTIVITIESDETAILS_SUCCESS",
  POST_REGENERATESELECTEDACTIVITIESDETAILS_FAILURE:
    "POST_REGENERATESELECTEDACTIVITIESDETAILS_FAILURE",

  REGENERATESELECTEDGOALDETAILS_REQUEST:
    "REGENERATESELECTEDGOALDETAILS_REQUEST",
  REGENERATESELECTEDGOALDETAILS_SUCCESS:
    "REGENERATESELECTEDGOALDETAILS_SUCCESS",
  REGENERATESELECTEDGOALDETAILS_FAILURE:
    "REGENERATESELECTEDGOALDETAILS_FAILURE",

  LIKEORDISLIKERECOMMENDATION_REQUEST: "LIKEORDISLIKERECOMMENDATION_REQUEST",
  LIKEORDISLIKERECOMMENDATION_SUCCESS: "LIKEORDISLIKERECOMMENDATION_SUCCESS",
  LIKEORDISLIKERECOMMENDATION_FAILURE: "LIKEORDISLIKERECOMMENDATION_FAILURE", //LIKEORDISLIKERECOMMENDATION

  GETALLGLOBALCODESWITHCATEGORY1_REQUEST:
    "GETALLGLOBALCODESWITHCATEGORY1_REQUEST",
  GETALLGLOBALCODESWITHCATEGORY1_SUCCESS:
    "GETALLGLOBALCODESWITHCATEGORY1_SUCCESS",
  GETALLGLOBALCODESWITHCATEGORY1_FAILURE:
    "GETALLGLOBALCODESWITHCATEGORY1_FAILURE", //LIKEORDISLIKERECOMMENDATION

  GET_RECOMMENDATION_QUESTION_SUCCESS: "GET_RECOMMENDATION_QUESTION_SUCCESS",
  GET_RECOMMENDATION_QUESTION_FAILURE: "GET_RECOMMENDATION_QUESTION_FAILURE",
  GET_RECOMMENDATION_QUESTION_REQUEST: "GET_RECOMMENDATION_QUESTION_REQUEST",
};
