export default {
  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_REQUEST:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_REQUEST",
  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_SUCCESS:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_SUCCESS",
  GET_GETSEEKERWELLNESSPLANDETAILSASYNC_FAILURE:
    "GET_GETSEEKERWELLNESSPLANDETAILSASYNC_FAILURE",

  GET_SEEKER_PERSONAL_INFO_REQUEST: "GET_SEEKER_PERSONAL_INFO_REQUEST",
  GET_SEEKER_PERSONAL_INFO_SUCCESS: "GET_SEEKER_PERSONAL_INFO_SUCCESS",
  GET_SEEKER_PERSONAL_INFO_FAILURE: "GET_SEEKER_PERSONAL_INFO_FAILURE",

  PUT_UPDATE_SEEKER_PERSONALINFO_REQUEST:
    "PUT_UPDATE_SEEKER_PERSONALINFO_REQUEST",
  PUT_UPDATE_SEEKER_PERSONALINFO_SUCCESS:
    "PUT_UPDATE_SEEKER_PERSONALINFO_SUCCESS",
  PUT_UPDATE_SEEKER_PERSONALINFO_FAILURE:
    "PUT_UPDATE_SEEKER_PERSONALINFO_FAILURE",

  GET_GETALLFROMIMAGES_REQUEST: "GET_GETALLFROMIMAGES_REQUEST",
  GET_GETALLFROMIMAGES_SUCCESS: "GET_GETALLFROMIMAGES_SUCCESS",
  GET_GETALLFROMIMAGES_FAILURE: "GET_GETALLFROMIMAGES_FAILURE",

  POST_UPLOADSEKKER_PROFILE_PICTURE_REQUEST:
    "POST_UPLOADSEKKER_PROFILE_PICTURE_REQUEST",
  POST_UPLOADSEKKER_PROFILE_PICTURE_SUCCESS:
    "POST_UPLOADSEKKER_PROFILE_PICTURE_SUCCESS",
  POST_UPLOADSEKKER_PROFILE_PICTURE_FAILURE:
    "POST_UPLOADSEKKER_PROFILE_PICTURE_FAILURE",

  POST_CREATEGOALANDASPIRATIONS_REQUEST:
    "POST_CREATEGOALANDASPIRATIONS_REQUEST",
  POST_CREATEGOALANDASPIRATIONS_SUCCESS:
    "POST_CREATEGOALANDASPIRATIONS_SUCCESS",
  POST_CREATEGOALANDASPIRATIONS_FAILURE:
    "POST_CREATEGOALANDASPIRATIONS_FAILURE",

  POST_ADDEMAIL_PHONENUMBER_REQUEST: "POST_ADDEMAIL_PHONENUMBER_REQUEST",
  POST_ADDEMAIL_PHONENUMBER_SUCCESS: "POST_ADDEMAIL_PHONENUMBER_SUCCESS",
  POST_ADDEMAIL_PHONENUMBER_FAILURE: "POST_ADDEMAIL_PHONENUMBER_FAILURE",

  POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_REQUEST:
    "POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_REQUEST",
  POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_SUCCESS:
    "POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_SUCCESS",
  POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_FAILURE:
    "POST_VERIFYSEEKEREMAILORPHONENUMBER_OTP_FAILURE",

  POST_SEEKER_ONBOARDING_STEPSANSWER_REQUEST:
    "POST_SEEKER_ONBOARDING_STEPSANSWER_REQUEST",
  POST_SEEKER_ONBOARDING_STEPSANSWER_SUCCESS:
    "POST_SEEKER_ONBOARDING_STEPSANSWER_SUCCESS",
  POST_SEEKER_ONBOARDING_STEPSANSWER_FAILURE:
    "POST_SEEKER_ONBOARDING_STEPSANSWER_FAILURE",

  GET_GETCONSENTFORMBYTYPE_REQUEST: "GET_GETCONSENTFORMBYTYPE_REQUEST",
  GET_GETCONSENTFORMBYTYPE_SUCCESS: "GET_GETCONSENTFORMBYTYPE_SUCCESS",
  GET_GETCONSENTFORMBYTYPE_FAILURE: "GET_GETCONSENTFORMBYTYPE_FAILURE",

  GET_USER_PREFERENCES_REQUEST: "GET_USER_PREFERENCES_REQUEST",
  GET_USER_PREFERENCES_SUCCESS: "GET_USER_PREFERENCES_SUCCESS",
  GET_USER_PREFERENCES_FAILURE: "GET_USER_PREFERENCES_FAILURE",

  GET_PREFERENCES_STEPSBYCODE_ID_REQUEST:
    "GET_PREFERENCES_STEPSBYCODE_ID_REQUEST",
  GET_PREFERENCES_STEPSBYCODE_ID_SUCCESS:
    "GET_PREFERENCES_STEPSBYCODE_ID_SUCCESS",
  GET_PREFERENCES_STEPSBYCODE_ID_FAILURE:
    "GET_PREFERENCES_STEPSBYCODE_ID_FAILURE",

  POST_PREFERENCE_STEP_ANSWER_REQUEST: "POST_PREFERENCE_STEP_ANSWER_REQUEST",
  POST_PREFERENCE_STEP_ANSWER_SUCCESS: "POST_PREFERENCE_STEP_ANSWER_SUCCESS",
  POST_PREFERENCE_STEP_ANSWER_FAILURE: "POST_PREFERENCE_STEP_ANSWER_FAILURE",

  GET_SENDCONTACTFORM_REQUEST: "GET_SENDCONTACTFORM_REQUEST",
  GET_SENDCONTACTFORM_SUCCESS: "GET_SENDCONTACTFORM_SUCCESS",
  GET_SENDCONTACTFORM_FAILURE: "GET_SENDCONTACTFORM_FAILURE",

  GET_CHANGEPASSWORD_REQUEST: "GET_CHANGEPASSWORD_REQUEST",
  GET_CHANGEPASSWORD_SUCCESS: "GET_CHANGEPASSWORD_SUCCESS",
  GET_CHANGEPASSWORD_FAILURE: "GET_CHANGEPASSWORD_FAILURE",

  SAVE_EXPLORER_PREFERENCES_REQUEST: "SAVE_EXPLORER_PREFERENCES_REQUEST",
  SAVE_EXPLORER_PREFERENCES_SUCCESS: "SAVE_EXPLORER_PREFERENCES_SUCCESS",
  SAVE_EXPLORER_PREFERENCES_FAILURE: "SAVE_EXPLORER_PREFERENCES_FAILURE",

  GET_USERMEDICAL_HISTORY_REQUEST: "GET_USERMEDICAL_HISTORY_REQUEST",
  GET_USERMEDICAL_HISTORY_SUCCESS: "GET_USERMEDICAL_HISTORY_SUCCESS",
  GET_USERMEDICAL_HISTORY_FAILURE: "GET_USERMEDICAL_HISTORY_FAILURE",

  GET_MEDICALHISTORY_STEPBYCODE_ID_REQUEST:
    "GET_MEDICALHISTORY_STEPBYCODE_ID_REQUEST",
  GET_MEDICALHISTORY_STEPBYCODE_ID_SUCCESS:
    "GET_MEDICALHISTORY_STEPBYCODE_ID_SUCCESS",
  GET_MEDICALHISTORY_STEPBYCODE_ID_FAILURE:
    "GET_MEDICALHISTORY_STEPBYCODE_ID_FAILURE",

  POST_MEDICALHISTORY_STEPANSWER_REQUEST:
    "POST_MEDICALHISTORY_STEPANSWER_REQUEST",
  POST_MEDICALHISTORY_STEPANSWER_SUCCESS:
    "POST_MEDICALHISTORY_STEPANSWER_SUCCESS",
  POST_MEDICALHISTORY_STEPANSWER_FAILURE:
    "POST_MEDICALHISTORY_STEPANSWER_FAILURE",

  UPDATE_USER_SKIPPED_CATEGORY_REQUEST: "UPDATE_USER_SKIPPED_CATEGORY_REQUEST",
  UPDATE_USER_SKIPPED_CATEGORY_SUCCESS: "UPDATE_USER_SKIPPED_CATEGORY_SUCCESS",
  UPDATE_USER_SKIPPED_CATEGORY_FAILURE: "UPDATE_USER_SKIPPED_CATEGORY_FAILURE",

  GET_USER_SKIPPED_CATEGORY_REQUEST: "GET_USER_SKIPPED_CATEGORY_REQUEST",
  GET_USER_SKIPPED_CATEGORY_SUCCESS: "GET_USER_SKIPPED_CATEGORY_SUCCESS",
  GET_USER_SKIPPED_CATEGORY_FAILURE: "GET_USER_SKIPPED_CATEGORY_FAILURE",

  GET_WELLNESSPLAN_DETAILS_REQUEST: "GET_WELLNESSPLAN_DETAILS_REQUEST",
  GET_WELLNESSPLAN_DETAILS_SUCCESS: "GET_WELLNESSPLAN_DETAILS_SUCCESS",
  GET_WELLNESSPLAN_DETAILS_FAILURE: "GET_WELLNESSPLAN_DETAILS_FAILURE",

  POST_GETUSERSTEPANDOPTIONSWITHANSWERS_REQUEST:
    "POST_GETUSERSTEPANDOPTIONSWITHANSWERS_REQUEST",
  POST_GETUSERSTEPANDOPTIONSWITHANSWERS_SUCCESS:
    "POST_GETUSERSTEPANDOPTIONSWITHANSWERS_SUCCESS",
  POST_GETUSERSTEPANDOPTIONSWITHANSWERS_FAILURE:
    "POST_GETUSERSTEPANDOPTIONSWITHANSWERS_FAILURE",

  POST_SAVEANDUPDATEUSER_ANSWER_REQUEST:
    "POST_SAVEANDUPDATEUSER_ANSWER_REQUEST",
  POST_SAVEANDUPDATEUSER_ANSWER_SUCCESS:
    "POST_SAVEANDUPDATEUSER_ANSWER_SUCCESS",
  POST_SAVEANDUPDATEUSER_ANSWER_FAILURE:
    "POST_SAVEANDUPDATEUSER_ANSWER_FAILURE",

  //user https://dev-api.zumlo.co/user-service/api/v1/User/CreateUserDeviceInfo
  //  CREATE_USERDEVICE_INFO
  GET_CREATE_USERDEVICE_INFO_REQUEST: "GET_CREATE_USERDEVICE_INFO_REQUEST",
  GET_CREATE_USERDEVICE_INFO_SUCCESS: "GET_CREATE_USERDEVICE_INFO_SUCCESS",
  GET_CREATE_USERDEVICE_INFO_FAILURE: "GET_CREATE_USERDEVICE_INFO_FAILURE",
  //SESSION_TIMEOUT
  GET_SESSION_TIMEOUT_REQUEST: "GET_SESSION_TIMEOUT_REQUEST",
  GET_SESSION_TIMEOUT_SUCCESS: "GET_SESSION_TIMEOUT_SUCCESS",
  GET_SESSION_TIMEOUT_FAILURE: "GET_SESSION_TIMEOUT_FAILURE",
  //UPDATEACTIVITYSCHEDULEDTIMEWITHGUID
  UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_REQUEST:
    "UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_REQUEST",
  UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_SUCCESS:
    "UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_SUCCESS",
  UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_FAILURE:
    "UPDATEACTIVITYSCHEDULEDTIMEWITHGUID_FAILURE",
};
