export default {
  GET_GETUSERWELLNESSPLANPROGRESS_REQUEST:
    "GET_GETUSERWELLNESSPLANPROGRESS_REQUEST",
  GET_GETUSERWELLNESSPLANPROGRESS_SUCCESS:
    "GET_GETUSERWELLNESSPLANPROGRESS_SUCCESS",
  GET_GETUSERWELLNESSPLANPROGRESS_FAILURE:
    "GET_GETUSERWELLNESSPLANPROGRESS_FAILURE",

  GET_GETUSERGOALPROGRESSBYID_REQUEST: "GET_GETUSERGOALPROGRESSBYID_REQUEST",
  GET_GETUSERGOALPROGRESSBYID_SUCCESS: "GET_GETUSERGOALPROGRESSBYID_SUCCESS",
  GET_GETUSERGOALPROGRESSBYID_FAILURE: "GET_GETUSERGOALPROGRESSBYID_FAILURE",

  GET_GETUSERGOALPROGRESS_REQUEST: "GET_GETUSERGOALPROGRESS_REQUEST",
  GET_GETUSERGOALPROGRESS_SUCCESS: "GET_GETUSERGOALPROGRESS_SUCCESS",
  GET_GETUSERGOALPROGRESS_FAILURE: "GET_GETUSERGOALPROGRESS_FAILURE",

  GET_GETUSERACTIVITYPROGRESSBYID_REQUEST:
    "GET_GETUSERACTIVITYPROGRESSBYID_REQUEST",
  GET_GETUSERACTIVITYPROGRESSBYID_SUCCESS:
    "GET_GETUSERACTIVITYPROGRESSBYID_SUCCESS",
  GET_GETUSERACTIVITYPROGRESSBYID_FAILURE:
    "GET_GETUSERACTIVITYPROGRESSBYID_FAILURE",

  GET_GETUSERACTIVITYPROGRESS_REQUEST: "GET_GETUSERACTIVITYPROGRESS_REQUEST",
  GET_GETUSERACTIVITYPROGRESS_SUCCESS: "GET_GETUSERACTIVITYPROGRESS_SUCCESS",
  GET_GETUSERACTIVITYPROGRESS_FAILURE: "GET_GETUSERACTIVITYPROGRESS_FAILURE",
};
